# Generated by Django 4.2.2 on 2023-06-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_remove_profile_linkedin_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_link',
            new_name='linkedIn_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
