# Generated by Django 4.2.2 on 2023-06-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
